# Russian -> English for the /en/ pages. Keys are matched after collapsing whitespace
# (incl. non-breaking spaces). Facts are the user's confirmed ones; nothing added.
T = {
# meta / chrome
"Денис Бержанин — студент-маркетолог, ищу стажировку в сфере маркетинга. Исследования рынка и потребителей, позиционирование, брендинг. Опыт, резюме и сертификаты.":
 "Denis Berzhanin — marketing student looking for a marketing internship. Market and consumer research, positioning, branding. Projects, CV and certificates.",
"Денис Бержанин": "Denis Berzhanin",
"Денис Бержанин — маркетолог · исследования и брендинг": "Denis Berzhanin — marketing · research & branding",
"Денис Бержанин — маркетолог · исследования и брендинг, портрет и направления работ": "Denis Berzhanin — marketing · research & branding, portrait and areas of work",
"Резюме — Денис Бержанин · исследования и брендинг": "CV — Denis Berzhanin · research & branding",
"Портфолио": "Portfolio",
"Перейти к содержанию": "Skip to content",
"Перейти к резюме": "Skip to CV",
"Berzhanin Denis — на главную": "Berzhanin Denis — home",
"Основная навигация": "Main navigation",
"Обо мне": "About",
"Опыт": "Experience",
"Работы": "Work",
"Резюме": "CV",
"Контакты": "Contact",
"Написать": "Message me",
"Открыть меню": "Open menu",
"Навигация по сайту": "Site navigation",
"Закрыть меню": "Close menu",
"Навигация": "Navigation",
"Меню сайта": "Site menu",
"Главная": "Home",
"Почта": "Email",
"Телефон": "Phone",
"Связаться со мной": "Get in touch",
"Резюме & портфолио": "CV & portfolio",
"Разделы страницы": "Page sections",
"На главную": "Home",
"Наверх ↑": "Back to top ↑",
# hero
"Чёрно-белый портрет Дениса Бержанина": "Black-and-white portrait of Denis Berzhanin",
"Ищу стажировку в сфере маркетинга. Исследования и брендинг — резюме и опыт": "Looking for a marketing internship. Research & branding — CV and experience",
"Ищу стажировку в сфере маркетинга": "Looking for a marketing internship",
"Денис Бержанин —": "Denis Berzhanin —",
"Исследования": "Research",
"& брендинг": "& branding",
"Специализируюсь на анализе рынков, потребительском поведении и позиционировании продуктов.":
 "I specialise in market analysis, consumer behaviour and product positioning.",
"Резюме и опыт": "CV and experience",
"Листайте вниз": "Scroll down",
"Остановить движение имени": "Pause the moving name",
# about
"Маркетинг · исследования · брендинг": "Marketing · research · branding",
"Понять людей.": "Understand people.",
"Найти смысл.": "Find the insight.",
"Предложить решение.": "Propose a solution.",
"Денис Бержанин — студент-маркетолог. Специализируюсь на анализе рынков, потребительском поведении и позиционировании продуктов.":
 "Denis Berzhanin — marketing student. I specialise in market analysis, consumer behaviour and product positioning.",
"3-й курс Финансового университета.": "3rd-year student at the Financial University, Moscow.",
"Ищу стажировку в сфере маркетинга.": "Looking for a marketing internship.",
"Дизайн помогает мне наглядно представлять выводы.": "Design helps me present findings clearly.",
# experience (home)
"Проектный опыт": "Project experience",
"Исследовать · анализировать · представлять": "Research · analyse · present",
"От задачи к решению": "From problem to solution",
"01 / Исследования и брендинг": "01 / Research & branding",
"ООО «Неровилль»": "Nerovill LLC",
"Исследование по заказу компании: опрос ~100 человек и 7 глубинных интервью. Показал на примерах брендов, что вода из одной скважины может отличаться в цене более чем в 2 раза. Лично защитил рекомендации по ребрендингу — заказчик принял их все.":
 "Research commissioned by the company: a survey of ~100 people and 7 in-depth interviews. Using brand examples, showed that water from the same well can differ in price by more than 2×. Personally presented the rebranding recommendations — the client accepted all of them.",
"02 / Курсовая работа · 2026 · Отлично": "02 / Coursework · 2026 · Grade: excellent",
"Разработал стратегию развития нового B2B-направления: позиционирование, коммуникация с корпоративной аудиторией, план на 6 месяцев, бюджет и KPI. Финансово обосновал жизнеспособность решения.":
 "Developed a strategy for a new B2B line: positioning, communication with corporate clients, a 6-month plan, budget and KPIs. Built the financial case for its viability.",
"03 / Курсовая работа · 2025 · Отлично": "03 / Coursework · 2025 · Grade: excellent",
"Базовая линейка одежды": "Basic apparel line",
"Сформировал go-to-market модель для 5 товарных категорий: целевая аудитория, ценностное предложение, ассортимент, цены, каналы продаж и бюджет запуска.":
 "Built a go-to-market model for 5 product categories: target audience, value proposition, range, pricing, sales channels and launch budget.",
"04 / Аналитика и защита решений": "04 / Analytics & pitching",
"Кейс-чемпионат ВТБ": "VTB Bank case championship",
"За три дня командой построили модель на данных по всей Москве, которая определяет лучшие места для банкоматов. Защитили решение перед представителями банка.":
 "In three days our team built a data model covering all of Moscow that identifies the best locations for ATMs. We pitched the solution to the bank's representatives.",
"05 / Работа с командами": "05 / Team leadership",
"«Я в деле»": "Ya v Dele",
"Наставник двух команд: обучение, задачи и дедлайны, поддержка участников. Обе команды довели свои проекты до защиты. Ранее — участник проекта «БЕЗ ТАБУ».":
 "Mentor to two teams in a youth entrepreneurship programme: training, tasks and deadlines, support for participants. Both teams took their projects through to the final pitch. Earlier — participant in the “BEZ TABU” educational project.",
"Резюме, навыки и награды": "CV, skills and awards",
# portfolio
"Визуальные работы": "Visual work",
"Дополнительный навык": "Additional skill",
"Как я оформляю идеи": "How I present ideas",
"Дизайн — ещё один инструмент: помогает объяснять идеи, результаты исследований и логику решений.":
 "Design is one more tool: it helps explain ideas, research findings and the logic behind decisions.",
"Фильтры работ": "Work filters",
"Направления": "Categories",
"Все": "All",
"Презентации": "Presentations",
"Деловые и творческие": "Business and creative",
"7 работ": "7 works",
"Интерфейсы": "Interfaces",
"Веб и приложения": "Web and apps",
"2 работы": "2 works",
"Айдентика и графика": "Identity & graphics",
"Айдентика": "Identity",
"и графика": "& graphics",
"Логотипы и постер": "Logos and a poster",
"3 работы": "3 works",
"Все работы": "All work",
"12 работ": "12 works",
"Все работы ↗": "All work ↗",
"Смотреть ↗": "View ↗",
"Смотреть": "View",
"Ещё 5 презентаций": "5 more presentations",
"Страховой рынок": "Insurance market",
"Смотреть: Страховой рынок": "View: Insurance market",
"Российский страховой рынок: I полугодие 2026 — слайд с ключевыми показателями": "Russian insurance market, H1 2026 — slide with key figures",
"Аналитический слайд": "Analytical slide",
"Обработка заказов": "Order processing",
"Смотреть: Обработка заказов": "View: Order processing",
"Бизнес-процесс обработки заказов в небольшом интернет-магазине — чёрно-розовая обложка": "Order-processing business flow for a small online store — black and pink cover",
"Обложка · Бизнес-процесс": "Cover · Business process",
"Смотреть: Creator Gym": "View: Creator Gym",
"Creator Gym — чёрная обложка с хромированными 3D-фигурами": "Creator Gym — black cover with chrome 3D shapes",
"Обложка · 3D-графика": "Cover · 3D graphics",
"Смотреть: Unity of Command": "View: Unity of Command",
"Unity of Command — бордовая типографическая обложка. Ekaterina Singilevtseva и Denis Berhzhanin": "Unity of Command — burgundy typographic cover. Ekaterina Singilevtseva and Denis Berhzhanin",
"Обложка · Совместная работа": "Cover · Joint work",
"Смотреть: Россия и русская культура": "View: Russia and Russian culture",
"Россия и русская культура": "Russia and Russian culture",
"Россия — коллаж из архитектуры и культурных символов": "Russia — collage of architecture and cultural symbols",
"Русская культура / Russian Culture — бело-синяя обложка с цветами": "Russian Culture — white and blue cover with flowers",
"Первые слова / Words you can use today — красный слайд с русскими словами и переводами": "Words you can use today — red slide with Russian words and translations",
"Коллажи · 3 слайда": "Collages · 3 slides",
"Смотреть: Дворцовые здания": "View: Palace buildings",
"Дворцовые здания": "Palace buildings",
"Дворцовые здания — чёрно-белый архитектурный коллаж": "Palace buildings — black-and-white architectural collage",
"Коллаж · Текстуры": "Collage · Textures",
"Смотреть: 3D-композиция": "View: 3D composition",
"3D-композиция": "3D composition",
"Thank you — финальный слайд с фиолетовыми и зелёными 3D-фигурами": "Thank you — closing slide with purple and green 3D shapes",
"Финальный слайд": "Closing slide",
"Смотреть: Learning Atlas": "View: Learning Atlas",
"Learning Atlas — карта подготовки к экзаменам, карточки предметов и мобильная версия": "Learning Atlas — exam-prep map, subject cards and mobile version",
"Концепт учебного сервиса · Веб и мобильный экран": "Study service concept · Web and mobile",
"Смотреть: EON VPN": "View: EON VPN",
"EON VPN — экраны подключения, тарифов, входа, подтверждения email, восстановления пароля и настроек": "EON VPN — connection, plans, sign-in, email confirmation, password recovery and settings screens",
"Дизайн мобильного приложения": "Mobile app design",
"Смотреть: .FAUX": "View: .FAUX",
".FAUX — чёрный геометрический логотип на белом фоне": ".FAUX — black geometric logo on white",
"Логотип · Геометрический знак": "Logo · Geometric mark",
"Смотреть: Голубой леттеринг": "View: Blue lettering",
"Голубой леттеринг": "Blue lettering",
"Голубой логотип с рисованными буквами и многослойным контуром": "Blue logo with hand-drawn letters and a layered outline",
"Логотип · Рисованные буквы": "Logo · Hand lettering",
"Смотреть: Я устал": "View: “I’m tired” poster",
"Я устал": "“I’m tired” poster",
"Я устал — постер со статуей ангела, светлым нимбом и ярко-розовой типографикой": "“I’m tired” — poster with an angel statue, a light halo and bright pink type (Russian text)",
"Постер · Типографика и коллаж": "Poster · Type and collage",
# contact
"Давайте": "Let’s",
"знакомиться": "talk",
"К работам": "See work",
"Посмотрите": "Take a look",
"мои работы": "at my work",
# viewer
"Закрыть просмотр": "Close viewer",
"Изображение работы": "Work image",
"Прокрутите вправо, чтобы посмотреть все экраны.": "Scroll right to see all screens.",
"Загрузка изображения…": "Loading image…",
"Предыдущее изображение": "Previous image",
"Следующее изображение": "Next image",
"Исходное изображение ↗": "Original image ↗",
"Открыть изображение ↗": "Open image ↗",
"Закрыть сертификат": "Close certificate",
"Открыть PDF ↗": "Open PDF ↗",
"Закрыть фотографии": "Close photos",
"Предыдущая фотография": "Previous photo",
"Следующая фотография": "Next photo",
"Открыть оригинал ↗": "Open original ↗",
# resume intro
"Награды": "Awards",
"Английский": "English",
"Денис": "Denis",
"Бержанин": "Berzhanin",
"Маркетинг.": "Marketing.",
"Исследования и брендинг.": "Research & branding.",
"Портрет Дениса Бержанина": "Portrait of Denis Berzhanin",
"Опыт, навыки, образование": "Experience, skills, education",
"3 диплома и 3 сертификата": "3 award diplomas and 3 certificates",
"Презентации, интерфейсы, графика": "Presentations, interfaces, graphics",
"Скачать резюме": "Download CV",
"PDF · 2,9 МБ": "PDF · RU",
"Изучаю людей.": "I study people.",
"Нахожу закономерности.": "I find patterns.",
"Объясняю решения.": "I explain decisions.",
"Цель": "Goal",
"Стажировка в сфере маркетинга": "Marketing internship",
"Язык": "Languages",
"Английский — CEFR B2": "English — CEFR B2 · Russian — native",
# event photos
"Фотографии с проектов и мероприятий": "Photos from projects and events",
"Открыть 5 фотографий: Я в деле": "Open 5 photos: Ya v Dele",
"Встреча с участниками проекта «Я в деле» за общим столом": "Meeting with Ya v Dele participants around a table",
"5 фото": "5 photos",
"Открыть фото: разбор проблемы с командой «Я в деле»": "Open photo: working through a problem with a Ya v Dele team",
"Разбор формулировки проблемы с командой «Я в деле»": "Working through a problem statement with a Ya v Dele team",
"Работа с командой": "Working with a team",
"Открыть фото: обсуждение проекта с аудиторией": "Open photo: discussing a project with the audience",
"Денис обсуждает проект с аудиторией": "Denis discussing a project with the audience",
"Обсуждение проекта": "Project discussion",
"Открыть 3 фотографии: ВТБ": "Open 3 photos: VTB",
"Участники мероприятия ВТБ на сцене": "VTB event participants on stage",
"ВТБ · обучение и кейс": "VTB · training and case",
"3 фото": "3 photos",
"Открыть командную фотографию на мероприятии ВТБ": "Open team photo at the VTB event",
"Командная фотография на мероприятии ВТБ": "Team photo at the VTB event",
"ВТБ · команда": "VTB · team",
"Открыть фото обучения на мероприятии ВТБ": "Open photo of training at the VTB event",
"Обучение на мероприятии ВТБ": "Training at the VTB event",
"ВТБ · обучение": "VTB · training",
"Открыть групповую фотографию «Я в деле»": "Open group photo: Ya v Dele",
"Групповая фотография после встречи «Я в деле»": "Group photo after a Ya v Dele session",
"«Я в деле» · участники": "Ya v Dele · participants",
"Открыть фото обсуждения проекта за общим столом": "Open photo of a project discussion around a table",
"Обсуждение проекта «Я в деле» за общим столом": "Ya v Dele project discussion around a table",
"Обсуждение идей": "Discussing ideas",
"Открыть фотографию с мероприятия": "Open event photo",
"Фотография у стенда на мероприятии": "Photo at a stand during an event",
"Мероприятия": "Events",
"1 фото": "1 photo",
# education & cv rows
"Образование": "Education",
"Финансовый университет при Правительстве РФ": "Financial University under the Government of the Russian Federation",
"Направление 38.03.02 «Менеджмент», профиль «Маркетинг»": "Bachelor’s in Management (38.03.02), Marketing track",
"3-й курс · Высшая школа управления · группа МК24-3": "3rd year · Higher School of Management",
"исследование и брендинг": "research & branding",
"Задача": "Task",
"Исследование рынка и потребителей по заказу компании, рекомендации по ребрендингу и репозиционированию.": "Market and consumer research commissioned by the company; recommendations for rebranding and repositioning.",
"Что сделал": "What I did",
"Опрос ~100 человек и 7 глубинных интервью. На примерах брендов показал, что вода из одной скважины может отличаться в цене более чем в 2 раза за счёт бренда.":
 "A survey of ~100 people and 7 in-depth interviews. Using brand examples, showed that branding alone can make water from the same well differ in price by more than 2×.",
"Результат": "Result",
"Лично защитил рекомендации — заказчик принял их все.": "Personally presented the recommendations — the client accepted all of them.",
"курсовая работа · 2026": "coursework · 2026",
"Моя работа": "My work",
"Разработал стратегию развития нового B2B-направления: анализ PESTEL, SWOT и портфельных матриц, коммуникация с корпоративной аудиторией, план продвижения на 6 месяцев, бюджет и система KPI.":
 "Developed a strategy for a new B2B line: PESTEL, SWOT and portfolio-matrix analysis, communication with corporate clients, a 6-month promotion plan, budget and KPI system.",
"Финансово обосновал жизнеспособность решения. Защищена на «отлично».": "Built the financial case for its viability. Graded excellent.",
"Финансовые показатели — сценарные оценки; программа не запускалась.": "Financial figures are scenario estimates; the programme was not launched.",
"курсовая работа · 2025": "coursework · 2025",
"На основе анализа рынка и практик Lime сформировал go-to-market модель для 5 товарных категорий: целевая аудитория, ценностное предложение, ассортимент, цены, каналы продаж и бюджет запуска.":
 "Based on market analysis and Lime’s practices, built a go-to-market model for 5 product categories: target audience, value proposition, range, pricing, sales channels and launch budget.",
"Защищена на «отлично».": "Graded excellent.",
"Работа представляет концепцию выхода на рынок.": "The work is a market-entry concept.",
"наставник двух команд": "mentor to two teams",
"Моя роль": "My role",
"Обучал участников, ставил задачи и сроки, сопровождал проекты и готовил отчётность.": "Trained participants, set tasks and deadlines, guided projects and prepared reports.",
"Обе команды довели проекты до защиты.": "Both teams took their projects through to the final pitch.",
"Ранее": "Earlier",
"Участник образовательного проекта «БЕЗ ТАБУ».": "Participant in the “BEZ TABU” educational project.",
"командный проект": "team project",
"Определить лучшие места для банкоматов по всей Москве.": "Identify the best ATM locations across Moscow.",
"За три дня командой построили модель на данных и защитили решение перед представителями банка.": "In three days our team built a data model and pitched it to the bank’s representatives.",
"Проекты на главной ↗": "Projects on the home page ↗",
# tools
"Инструменты": "Tools",
"Анализ, исследования и AI": "Analysis, research and AI",
"Google Sheets и Forms": "Google Sheets & Forms",
"Google Sheets и Forms: 80%": "Google Sheets & Forms: 80%",
"изучаю": "learning",
"Яндекс Вордстат": "Yandex Wordstat",
"Яндекс Вордстат: 60%": "Yandex Wordstat: 60%",
"Яндекс Метрика": "Yandex Metrica",
"Яндекс Метрика: 40%": "Yandex Metrica: 40%",
"базовый уровень": "basic",
"Визуальная подача и организация": "Visual presentation and organisation",
"уверенно": "confident",
# skills
"Навыки": "Skills",
"Исследования и стратегия": "Research and strategy",
"Анализ рынка и конкурентов, сегментация, опросы и глубинные интервью. Первичные и вторичные данные, позиционирование, SWOT / PEST, 4P / 7P.":
 "Market and competitor analysis, segmentation, surveys and in-depth interviews. Primary and secondary data, positioning, SWOT / PEST, 4P / 7P.",
"Работа с людьми и решениями": "People and decisions",
"Сопровождение команд, постановка задач и дедлайнов, отчётность, презентация и защита результатов.": "Guiding teams, setting tasks and deadlines, reporting, presenting and defending results.",
"Публикации и выступления": "Publications and talks",
"Соавтор опубликованной статьи о брендинге на рынке безалкогольных напитков в журнале из перечня ВАК. Исследовательские работы и выступления на конференциях.":
 "Co-author of a published article on branding in the soft-drinks market (peer-reviewed journal on Russia’s Higher Attestation Commission list). Research papers and conference talks.",
"Визуальная подача": "Visual presentation",
"Дополнительный навык ": "Additional skill",
"Самостоятельно изучаю дизайн: презентации, концепты интерфейсов, логотипы и графика. Для меня важно и содержание, и то, насколько понятно оно представлено.":
 "Self-taught in design: presentations, interface concepts, logos and graphics. I care about both the content and how clearly it is presented.",
"Визуальные работы ↗": "Visual work ↗",
# awards
"I степень": "1st degree",
"· Неделя иностранного языка, 2025. Совместная работа с Екатериной Сингилейцевой.": "· Foreign Language Week, 2025. Joint work with Ekaterina Singileytseva.",
"II место": "2nd place",
"· «Брендинг в эпоху платформенной экономики», 2026.": "· “Branding in the Platform Economy” conference, 2026.",
"III степень": "3rd degree",
"· «Маркетинг России», 2025.": "· “Marketing of Russia” conference, 2025.",
"Посмотреть дипломы ↘": "See the diplomas ↘",
"Обучение": "Training",
"Международная Евразийская летняя школа ННГУ · 72 часа · 2026": "International Eurasian Summer School, Lobachevsky University · 72 hours · 2026",
"«Я в деле» · предпринимательский курс · 8 недель · 2024": "Ya v Dele · entrepreneurship course · 8 weeks · 2024",
"Английский · CEFR B2": "English · CEFR B2",
"язык": "language",
"Языковые сертификаты": "Language certificates",
"Языковой сертификат": "Language certificate",
"30 августа 2026": "30 August 2026",
"16 сентября 2026": "16 September 2026",
"Общий балл: 6.0 из 9": "Overall score: 6.0 out of 9",
"Общий балл: 110 из 160": "Overall score: 110 out of 160",
"Смотреть: IELTS Academic": "View: IELTS Academic",
"IELTS Academic: общий балл 6.0, CEFR B2": "IELTS Academic: overall 6.0, CEFR B2",
"Смотреть: Duolingo English Test": "View: Duolingo English Test",
"Duolingo English Test: общий балл 110, CEFR B2": "Duolingo English Test: overall 110, CEFR B2",
"Открыть PDF": "Open PDF",
"Публичная копия: дата рождения и личные номера скрыты.": "Public copy: date of birth and personal numbers are hidden.",
"3 диплома · 2025–2026": "3 diplomas · 2025–2026",
"степень": "degree",
"место": "place",
"Смотреть: Неделя иностранного языка — Диплом · I степени": "View: Foreign Language Week — 1st-degree diploma",
"Диплом · I степени: Неделя иностранного языка, 2025": "1st-degree diploma: Foreign Language Week, 2025",
"Диплом · I степени": "Diploma · 1st degree",
"Неделя иностранного языка": "Foreign Language Week",
"Финансовый университет": "Financial University",
"Совместная работа с Екатериной Сингилейцевой.": "Joint work with Ekaterina Singileytseva.",
": Неделя иностранного языка": ": Foreign Language Week",
"Смотреть: Брендинг в эпоху платформенной экономики — Диплом · II место": "View: Branding in the Platform Economy — 2nd-place diploma",
"Диплом · II место: Брендинг в эпоху платформенной экономики, 2026": "2nd-place diploma: Branding in the Platform Economy, 2026",
"Диплом · II место": "Diploma · 2nd place",
"Брендинг в эпоху платформенной экономики": "Branding in the Platform Economy",
"Финансовый университет · 5–6 июня": "Financial University · 5–6 June",
"Реклама на орбите: как брендам готовиться к новому каналу 2026 года и измерять его эффективность.": "Advertising in orbit: how brands can prepare for a new 2026 channel and measure its effectiveness.",
": Брендинг в эпоху платформенной экономики": ": Branding in the Platform Economy",
"Смотреть: Маркетинг России — Диплом · III степени": "View: Marketing of Russia — 3rd-degree diploma",
"Диплом · III степени: Маркетинг России, 2025": "3rd-degree diploma: Marketing of Russia, 2025",
"Диплом · III степени": "Diploma · 3rd degree",
"Маркетинг России": "Marketing of Russia",
"Брендинг в условиях цифровизации на рынке безалкогольных напитков.": "Branding amid digitalisation in the soft-drinks market.",
"Диплом PDF": "Diploma PDF",
": Маркетинг России": ": Marketing of Russia",
"Маркетинг России — сертификат докладчика": "Marketing of Russia — speaker certificate",
"Сертификат докладчика": "Speaker certificate",
"Участие": "Participation",
"и обучение": "& training",
"Смотреть: Международная Евразийская летняя школа — Сертификат · 72 часа": "View: International Eurasian Summer School — 72-hour certificate",
"Сертификат · 72 часа: Международная Евразийская летняя школа, 2026": "72-hour certificate: International Eurasian Summer School, 2026",
"Сертификат · 72 часа": "Certificate · 72 hours",
"Международная Евразийская летняя школа": "International Eurasian Summer School",
"ННГУ им. Н. И. Лобачевского · 28 июля–11 августа": "Lobachevsky University, Nizhny Novgorod · 28 July–11 August",
": Международная Евразийская летняя школа": ": International Eurasian Summer School",
"Смотреть: Экономическая психология — Сертификат участника": "View: Economic Psychology — participant certificate",
"Сертификат участника: Экономическая психология, 2025": "Participant certificate: Economic Psychology, 2025",
"Сертификат участника": "Participant certificate",
"Экономическая психология": "Economic Psychology",
"Нарастание психологической зависимости от интернет-шоппинга в молодёжной среде: тренд потребления или побег от реальности?": "Growing psychological dependence on online shopping among young people: a consumption trend or an escape from reality?",
": Экономическая психология": ": Economic Psychology",
"Смотреть: Я в деле — Сертификат · 8 недель": "View: Ya v Dele — 8-week certificate",
"Сертификат · 8 недель: Я в деле, 2024": "8-week certificate: Ya v Dele, 2024",
"Сертификат · 8 недель": "Certificate · 8 weeks",
"Я в деле": "Ya v Dele",
"Программа развития молодёжного предпринимательства · Москва": "Moscow youth entrepreneurship programme",
"Предпринимательский курс.": "Entrepreneurship course.",
": Я в деле": ": Ya v Dele",
}
